import './global.css';
import { Navbar } from '@org/shared-ui';

export const metadata = {
  title: 'Welcome to app1',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
