import { UserProvider } from '@auth0/nextjs-auth0/client';
import './global.css';
import { Navbar } from '@org/shared-ui';

export const metadata = {
  title: 'Welcome to app1',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
